export const companiesData = [
  {
    companyId: 'COMP001',
    name: 'Microsoft India',
    logo: 'https://images.unsplash.com/photo-1642132652859-3ef5a1048fd1?w=128&auto=format&fit=crop&q=60',
    industry: 'Technology & Cloud',
    type: 'MNC / Product',
    website: 'https://careers.microsoft.com',
    location: 'Hyderabad / Bengaluru',
    city: 'Hyderabad',
    state: 'Telangana',
    description: 'Global technology leader in software development, cloud computing, and enterprise AI solutions.',
    employeeCount: '15,000+ (India)',
    contactPerson: 'Sneha Kulkarni',
    contactEmail: 'sneha.k@microsoft.com',
    contactPhone: '+91 98112 34567',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '44.0 LPA',
    activeDrivesCount: 1,
    totalHires: 14
  },
  {
    companyId: 'COMP002',
    name: 'Google India',
    logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=128&auto=format&fit=crop&q=60',
    industry: 'Technology & Search',
    type: 'MNC / Product',
    website: 'https://careers.google.com',
    location: 'Bengaluru / Hyderabad',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Pioneering global tech company specializing in search, AI, cloud systems, and distributed platforms.',
    employeeCount: '10,000+ (India)',
    contactPerson: 'Anand Nair',
    contactEmail: 'anand.nair@google.com',
    contactPhone: '+91 98200 11223',
    status: 'Active',
    tier: 'Tier 1 (Super Dream)',
    averagePackage: '48.0 LPA',
    activeDrivesCount: 1,
    totalHires: 8
  },
  {
    companyId: 'COMP003',
    name: 'Amazon Web Services',
    logo: 'https://images.unsplash.com/photo-1523474253243-231a4be489e2?w=128&auto=format&fit=crop&q=60',
    industry: 'Cloud & E-Commerce',
    type: 'MNC / Product',
    website: 'https://amazon.jobs',
    location: 'Bengaluru / Hyderabad',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'World leading cloud infrastructure and e-commerce platform delivering high-scale services.',
    employeeCount: '100,000+ (India)',
    contactPerson: 'Priyanka Sen',
    contactEmail: 'psen@amazon.com',
    contactPhone: '+91 98300 44556',
    status: 'Active',
    tier: 'Tier 1 (Super Dream)',
    averagePackage: '36.0 LPA',
    activeDrivesCount: 1,
    totalHires: 12
  },
  {
    companyId: 'COMP004',
    name: 'Zomato',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=128&auto=format&fit=crop&q=60',
    industry: 'Consumer Internet & Tech',
    type: 'Product / Tech Unicorn',
    website: 'https://www.zomato.com/careers',
    location: 'Gurugram, Haryana',
    city: 'Gurugram',
    state: 'Haryana',
    description: "India's premier food ordering, delivery, and dining platform powering quick-commerce at massive scale.",
    employeeCount: '5,000+',
    contactPerson: 'Aditya Verma',
    contactEmail: 'aditya.v@zomato.com',
    contactPhone: '+91 99100 88231',
    status: 'Active',
    tier: 'Tier 1 (Super Dream)',
    averagePackage: '28.0 LPA',
    activeDrivesCount: 1,
    totalHires: 8
  },
  {
    companyId: 'COMP005',
    name: 'Swiggy',
    logo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=128&auto=format&fit=crop&q=60',
    industry: 'Quick Commerce & Tech',
    type: 'Product / Tech Unicorn',
    website: 'https://careers.swiggy.com',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Leading convenience commerce platform with deep technology in routing, AI, and delivery logistics.',
    employeeCount: '6,000+',
    contactPerson: 'Neha Kapoor',
    contactEmail: 'neha.k@swiggy.in',
    contactPhone: '+91 98451 99887',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '24.0 LPA',
    activeDrivesCount: 1,
    totalHires: 6
  },
  {
    companyId: 'COMP006',
    name: 'Cisco Systems',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=128&auto=format&fit=crop&q=60',
    industry: 'Networking & Cybersecurity',
    type: 'MNC / Product',
    website: 'https://jobs.cisco.com',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Worldwide leader in networking and security solutions transforming modern digital infrastructures.',
    employeeCount: '12,000+ (India)',
    contactPerson: 'Karthik Nair',
    contactEmail: 'knair@cisco.com',
    contactPhone: '+91 98801 98765',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '16.5 LPA',
    activeDrivesCount: 1,
    totalHires: 12
  },
  {
    companyId: 'COMP007',
    name: 'Oracle India',
    logo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=128&auto=format&fit=crop&q=60',
    industry: 'Enterprise Database & Cloud',
    type: 'MNC / Product',
    website: 'https://www.oracle.com/careers',
    location: 'Bengaluru / Hyderabad / Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    description: 'Leader in enterprise software, database engineering, and cloud infrastructure.',
    employeeCount: '38,000+ (India)',
    contactPerson: 'Deepika Rao',
    contactEmail: 'deepika.rao@oracle.com',
    contactPhone: '+91 98102 33445',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '18.5 LPA',
    activeDrivesCount: 1,
    totalHires: 19
  },
  {
    companyId: 'COMP008',
    name: 'Deloitte USI',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=128&auto=format&fit=crop&q=60',
    industry: 'Management & Technology Consulting',
    type: 'MNC / Consulting',
    website: 'https://www2.deloitte.com',
    location: 'Hyderabad / Bengaluru / Gurugram',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Provider of industry-leading audit, consulting, tax, and tech advisory services for Fortune 500 corporations.',
    employeeCount: '50,000+ (India)',
    contactPerson: 'Pooja Hegde',
    contactEmail: 'pooja.hegde@deloitte.com',
    contactPhone: '+91 98450 12345',
    status: 'Active',
    tier: 'Tier 2',
    averagePackage: '11.5 LPA',
    activeDrivesCount: 1,
    totalHires: 36
  },
  {
    companyId: 'COMP009',
    name: 'PwC India',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=128&auto=format&fit=crop&q=60',
    industry: 'Consulting & Advisory',
    type: 'MNC / Consulting',
    website: 'https://www.pwc.in/careers',
    location: 'Mumbai / Gurugram / Bengaluru',
    city: 'Mumbai',
    state: 'Maharashtra',
    description: 'Global professional services network providing tech consulting, risk advisory, and tax solutions.',
    employeeCount: '20,000+',
    contactPerson: 'Vikram Joshi',
    contactEmail: 'vikram.j@pwc.com',
    contactPhone: '+91 98200 77665',
    status: 'Active',
    tier: 'Tier 2',
    averagePackage: '10.5 LPA',
    activeDrivesCount: 1,
    totalHires: 22
  },
  {
    companyId: 'COMP010',
    name: 'Tata Consultancy Services',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=60',
    industry: 'IT Services & Consulting',
    type: 'MNC / IT Services',
    website: 'https://www.tcs.com/careers',
    location: 'Pan India',
    city: 'Mumbai',
    state: 'Maharashtra',
    description: 'Leading global IT services, consulting, and business solutions organization with massive campus hiring programs.',
    employeeCount: '600,000+',
    contactPerson: 'Ramanathan Iyer',
    contactEmail: 'raman.iyer@tcs.com',
    contactPhone: '+91 98201 56789',
    status: 'Active',
    tier: 'Mass Recruiter',
    averagePackage: '8.0 LPA',
    activeDrivesCount: 1,
    totalHires: 142
  },
  {
    companyId: 'COMP011',
    name: 'Infosys Limited',
    logo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=128&auto=format&fit=crop&q=60',
    industry: 'IT Services & Digital Solutions',
    type: 'MNC / IT Services',
    website: 'https://www.infosys.com/careers',
    location: 'Bengaluru / Pune / Hyderabad',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Global leader in next-generation digital services and consulting navigating client digital transformation.',
    employeeCount: '320,000+',
    contactPerson: 'Sunita Rao',
    contactEmail: 'sunita.rao@infosys.com',
    contactPhone: '+91 98440 22331',
    status: 'Active',
    tier: 'Mass Recruiter',
    averagePackage: '8.0 LPA',
    activeDrivesCount: 1,
    totalHires: 98
  },
  {
    companyId: 'COMP012',
    name: 'Accenture India',
    logo: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=128&auto=format&fit=crop&q=60',
    industry: 'Professional Services & Tech',
    type: 'MNC / Consulting',
    website: 'https://www.accenture.com/in-en/careers',
    location: 'Pan India',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Global professional services company with leading capabilities in digital, cloud, and security.',
    employeeCount: '300,000+ (India)',
    contactPerson: 'Amitabh Sen',
    contactEmail: 'amitabh.sen@accenture.com',
    contactPhone: '+91 98111 44552',
    status: 'Active',
    tier: 'Tier 2',
    averagePackage: '9.2 LPA',
    activeDrivesCount: 1,
    totalHires: 75
  },
  {
    companyId: 'COMP013',
    name: 'Qualcomm India',
    logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=128&auto=format&fit=crop&q=60',
    industry: 'Semiconductors & Wireless',
    type: 'MNC / Hardware & Software',
    website: 'https://www.qualcomm.com/company/careers',
    location: 'Hyderabad / Bengaluru / Chennai',
    city: 'Hyderabad',
    state: 'Telangana',
    description: 'World leader in wireless tech, 5G chipsets, and AI silicon transforming how the world connects.',
    employeeCount: '16,000+ (India)',
    contactPerson: 'Suresh Varma',
    contactEmail: 'svarma@qualcomm.com',
    contactPhone: '+91 98490 66778',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '26.0 LPA',
    activeDrivesCount: 1,
    totalHires: 18
  },
  {
    companyId: 'COMP014',
    name: 'Texas Instruments',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=60',
    industry: 'Semiconductors & Analog',
    type: 'MNC / Hardware & Embedded',
    website: 'https://careers.ti.com',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Global semiconductor company designing and manufacturing analog and embedded processing chips.',
    employeeCount: '3,000+ (India)',
    contactPerson: 'Divya Nambiar',
    contactEmail: 'dnambiar@ti.com',
    contactPhone: '+91 98800 11335',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '21.0 LPA',
    activeDrivesCount: 1,
    totalHires: 10
  },
  {
    companyId: 'COMP015',
    name: 'L&T Technology Services',
    logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=128&auto=format&fit=crop&q=60',
    industry: 'Engineering R&D & IoT',
    type: 'MNC / Engineering Services',
    website: 'https://www.ltts.com/careers',
    location: 'Vadodara / Bengaluru / Mumbai',
    city: 'Vadodara',
    state: 'Gujarat',
    description: 'Listed subsidiary of Larsen & Toubro focused on Engineering R&D services across 5 major verticals.',
    employeeCount: '22,000+',
    contactPerson: 'Pradeep Joshi',
    contactEmail: 'pradeep.j@ltts.com',
    contactPhone: '+91 98250 88990',
    status: 'Active',
    tier: 'Tier 2',
    averagePackage: '8.2 LPA',
    activeDrivesCount: 1,
    totalHires: 45
  },
  {
    companyId: 'COMP016',
    name: 'Cognizant Technology',
    logo: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=128&auto=format&fit=crop&q=60',
    industry: 'IT Services & Digital',
    type: 'MNC / IT Services',
    website: 'https://careers.cognizant.com',
    location: 'Chennai / Hyderabad / Kolkata',
    city: 'Chennai',
    state: 'Tamil Nadu',
    description: 'Global technology company helping clients modernize technology, reimagine processes and transform experiences.',
    employeeCount: '250,000+ (India)',
    contactPerson: 'Shankar Pillai',
    contactEmail: 'shankar.p@cognizant.com',
    contactPhone: '+91 98401 22446',
    status: 'Active',
    tier: 'Mass Recruiter',
    averagePackage: '7.5 LPA',
    activeDrivesCount: 1,
    totalHires: 85
  },
  {
    companyId: 'COMP017',
    name: 'Schneider Electric',
    logo: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=128&auto=format&fit=crop&q=60',
    industry: 'Energy Management & Automation',
    type: 'MNC / Energy & Tech',
    website: 'https://www.se.com/in/en/about-us/careers',
    location: 'Bengaluru / Gurugram',
    city: 'Bengaluru',
    state: 'Karnataka',
    description: 'Global specialist in energy management and automation developing connected technologies and solutions.',
    employeeCount: '35,000+ (India)',
    contactPerson: 'Renu Sharma',
    contactEmail: 'renu.sharma@se.com',
    contactPhone: '+91 98108 66554',
    status: 'Active',
    tier: 'Tier 1 (Dream)',
    averagePackage: '14.0 LPA',
    activeDrivesCount: 1,
    totalHires: 15
  }
];
